-- Создание таблицы users_token
create table if not exists users_token
(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
accessToken VARCHAR(1000) UNIQUE
);

comment on column users_token.id is 'ID пользователя';
comment on column users_token.accessToken is 'Токен пользователя';