package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

type StructInfo struct {
	Name   string
	Fields []*ast.Field
}

var primitiveZero = map[string]string{
	"bool":    "false",
	"string":  `""`,
	"int":     "0",
	"int8":    "0",
	"int16":   "0",
	"int32":   "0",
	"int64":   "0",
	"uint":    "0",
	"uint8":   "0",
	"uint16":  "0",
	"uint32":  "0",
	"uint64":  "0",
	"uintptr": "0",
	"float32": "0",
	"float64": "0",
	"byte":    "0",
	"rune":    "0",
}

func main() {
	root := "."

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		name := info.Name()

		if name == ".git" ||
			path == "./cmd/reset" {
			return filepath.SkipDir
		}

		return processPackage(path)
	})

	if err != nil {
		panic(err)
	}
}

func processPackage(dir string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax,
		Dir: dir,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {

		var structs []StructInfo

		for _, file := range pkg.Syntax {

			for _, decl := range file.Decls {

				genDecl, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				if genDecl.Tok != token.TYPE {
					continue
				}

				if !hasResetComment(genDecl) {
					continue
				}

				for _, spec := range genDecl.Specs {

					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					structs = append(structs, StructInfo{
						Name:   typeSpec.Name.Name,
						Fields: st.Fields.List,
					})
				}
			}
		}

		if len(structs) == 0 {
			continue
		}

		if err := generateFile(dir, pkg.Name, structs); err != nil {
			return err
		}
	}

	return nil
}

func hasResetComment(d *ast.GenDecl) bool {
	if d.Doc == nil {
		return false
	}

	for _, c := range d.Doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}

	return false
}

func generateFile(dir, pkgName string, structs []StructInfo) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	for _, s := range structs {
		generateResetMethod(&buf, s)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	filename := filepath.Join(dir, "reset.gen.go")

	return os.WriteFile(filename, src, 0644)
}

func generateResetMethod(buf *bytes.Buffer, s StructInfo) {
	fmt.Fprintf(buf, "func (x *%s) Reset() {\n", s.Name)

	buf.WriteString(`
	if x == nil {
		return
	}
`)

	for _, field := range s.Fields {

		if len(field.Names) == 0 {
			continue
		}

		for _, name := range field.Names {
			generateFieldReset(buf, "x."+name.Name, field.Type)
		}
	}

	buf.WriteString("}\n\n")
}

func generateFieldReset(
	buf *bytes.Buffer,
	fieldName string,
	expr ast.Expr,
) {
	switch t := expr.(type) {

	case *ast.Ident:
		if zero, ok := primitiveZero[t.Name]; ok {
			fmt.Fprintf(buf, "\t%s = %s\n", fieldName, zero)
			return
		}

		fmt.Fprintf(buf,
			"\tif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n",
			fieldName,
		)
		buf.WriteString("\t\tresetter.Reset()\n")
		buf.WriteString("\t}\n")

	case *ast.ArrayType:
		fmt.Fprintf(buf,
			"\t%s = %s[:0]\n",
			fieldName,
			fieldName,
		)

	case *ast.MapType:
		fmt.Fprintf(buf,
			"\tclear(%s)\n",
			fieldName,
		)

	case *ast.StarExpr:
		generatePointerReset(buf, fieldName, t.X)
	}
}

func generatePointerReset(
	buf *bytes.Buffer,
	fieldName string,
	expr ast.Expr,
) {
	buf.WriteString("\tif " + fieldName + " != nil {\n")

	switch t := expr.(type) {

	case *ast.Ident:
		if zero, ok := primitiveZero[t.Name]; ok {

			fmt.Fprintf(
				buf,
				"\t\t*%s = %s\n",
				fieldName,
				zero,
			)

		} else {

			fmt.Fprintf(
				buf,
				"\t\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n",
				fieldName,
			)

			buf.WriteString("\t\t\tresetter.Reset()\n")
			buf.WriteString("\t\t}\n")
		}

	default:
		fmt.Fprintf(
			buf,
			"\t\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n",
			fieldName,
		)

		buf.WriteString("\t\t\tresetter.Reset()\n")
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString("\t}\n")
}
