// Code generated by reset generator. DO NOT EDIT.

package testmodel

func (x *User1) Reset() {

	if x == nil {
		return
	}
	x.ID = 0
	x.Name = ""
	x.Tags = x.Tags[:0]
	clear(x.Meta)
	if x.Counter != nil {
		*x.Counter = 0
	}
}
